/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Induwara Jayalath
 */
public class Admin_panel extends javax.swing.JFrame {

    /**
     * Creates new form Admin_panel
     */
    public Admin_panel() {
        initComponents();
    }

    public static int current_User = 0;
    public static int current_User_level = 0;

    public void showpanel(String cname) {
        CardLayout cL = (CardLayout) menu_panel.getLayout();
        cL.show(menu_panel, cname);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("mevanstock?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        itemsQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT i FROM Items i");
        itemsList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : itemsQuery.getResultList();
        peopleQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM People p");
        peopleList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : peopleQuery.getResultList();
        peopleQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM People p");
        peopleList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : peopleQuery1.getResultList();
        peopleQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM People p");
        peopleList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : peopleQuery2.getResultList();
        peopleQuery3 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM People p");
        peopleList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : peopleQuery3.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        menu_panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_items = new javax.swing.JTable();
        ID_field = new javax.swing.JTextField();
        Name_field = new javax.swing.JTextField();
        Quantity_field = new javax.swing.JTextField();
        Warrenty_field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Insert_butt = new javax.swing.JButton();
        Update_butt = new javax.swing.JButton();
        Delete_butt = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Description_field = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Name_ppl_Field = new javax.swing.JTextField();
        NIC_ppl_Field = new javax.swing.JTextField();
        Telephne_ppl_Field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ADD_ppl_butt = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jButton1.setText("Edit Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Add People");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 370, Short.MAX_VALUE)
                .addComponent(jButton6))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        menu_panel.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, itemsList, jTable1_items);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${itemID}"));
        columnBinding.setColumnName("Item ID");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${itemName}"));
        columnBinding.setColumnName("Item Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${itemQuantity}"));
        columnBinding.setColumnName("Item Quantity");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${itemWarrentyEndDate}"));
        columnBinding.setColumnName("Item Warrenty End Date");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${itemDescription}"));
        columnBinding.setColumnName("Item Description");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jTable1_items.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_itemsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_items);

        Quantity_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quantity_fieldActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("Name");

        jLabel3.setText("Quantity");

        jLabel4.setText("WarrentyEndDate");

        jLabel5.setText("Description");

        Insert_butt.setText("Insert");
        Insert_butt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert_buttActionPerformed(evt);
            }
        });

        Update_butt.setText("Update");
        Update_butt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_buttActionPerformed(evt);
            }
        });

        Delete_butt.setBackground(new java.awt.Color(255, 51, 51));
        Delete_butt.setText("Delete");
        Delete_butt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_buttActionPerformed(evt);
            }
        });

        Description_field.setColumns(10);
        Description_field.setRows(3);
        Description_field.setTabSize(5);
        jScrollPane2.setViewportView(Description_field);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ID_field)
                    .addComponent(Name_field)
                    .addComponent(Quantity_field)
                    .addComponent(Warrenty_field)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Insert_butt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Update_butt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Delete_butt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(35, 35, 35))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ID_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Quantity_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Warrenty_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Insert_butt)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Update_butt)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(Delete_butt))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        menu_panel.add(jPanel3, "card2");

        jPanel4.setBackground(new java.awt.Color(102, 255, 204));

        jLabel7.setText("Name");

        jLabel8.setText("NIC");

        jLabel9.setText("Telephone");

        ADD_ppl_butt.setText("ADD");
        ADD_ppl_butt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD_ppl_buttActionPerformed(evt);
            }
        });

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, peopleList3, jTable2);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${peopleName}"));
        columnBinding.setColumnName("People Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${peopleNIC}"));
        columnBinding.setColumnName("People NIC");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${peopleTP}"));
        columnBinding.setColumnName("People TP");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dateAdded}"));
        columnBinding.setColumnName("Date Added");
        columnBinding.setColumnClass(java.util.Date.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Telephne_ppl_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NIC_ppl_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(34, 34, 34)
                        .addComponent(Name_ppl_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addComponent(ADD_ppl_butt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name_ppl_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIC_ppl_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(ADD_ppl_butt, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telephne_ppl_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menu_panel.add(jPanel4, "card3");

        getContentPane().add(menu_panel, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        showpanel("card2");
        jLabel6.setText(null);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        showpanel("card3");
        clear_Fields();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void ADD_ppl_buttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD_ppl_buttActionPerformed
        String te="";
        if (te.equals(Name_ppl_Field.getText())) {
            JOptionPane.showMessageDialog(this, "Enter Values");
        } else {
            Connection con = dataBaseConnection.dataBaseConnectionMethod();
            String query = " insert into people values (null,?,?,?,null,?)";
            PreparedStatement preparedStmt;
            try {
                preparedStmt = con.prepareStatement(query);
                preparedStmt.setString(1, Name_ppl_Field.getText());
                preparedStmt.setString(2, NIC_ppl_Field.getText());
                preparedStmt.setInt(3, Integer.parseInt(Telephne_ppl_Field.getText()));
                preparedStmt.setDate(4, java.sql.Date.valueOf(java.time.LocalDate.now()));
                preparedStmt.execute();
                preparedStmt.close();
                JOptionPane.showMessageDialog(this, "Successfully added");
                clear_Fields();

            } catch (SQLException ex) {
                Logger.getLogger(Admin_panel.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Error occurd");
                clear_Fields();
            }
        }
    }//GEN-LAST:event_ADD_ppl_buttActionPerformed

    private void Insert_buttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insert_buttActionPerformed
        String SQLStat = "INSERT INTO items"
                + "(`itemID`,"
                + "`itemName`,"
                + "`itemQuantity`,"
                + "`itemWarrentyEndDate`,"
                + "`itemDescription`,"
                + "`itemAddedBy`)"
                + "VALUES(?,?,?,?,?,?);";

        try {
            PreparedStatement stmt = dataBaseConnection.dataBaseConnectionMethod().prepareStatement(SQLStat);
            stmt.setInt(1, Integer.parseInt(ID_field.getText()));
            stmt.setString(2, Name_field.getText());

            stmt.setInt(3, Integer.parseInt(Quantity_field.getText()));
            if (Warrenty_field.getText().equalsIgnoreCase("")) {
                stmt.setString(4, null);
            } else {
                stmt.setString(4, Warrenty_field.getText());
            }
            if (Description_field.getText().equalsIgnoreCase("")) {
                stmt.setString(5, null);
            } else {
                stmt.setString(5, Description_field.getText());
            }
            stmt.setInt(6, current_User);

            stmt.execute();
            stmt.close();
            JOptionPane.showMessageDialog(this, "Done");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            System.out.println(e.getMessage());
        }
        clear_Fields();
    }//GEN-LAST:event_Insert_buttActionPerformed

    private void jTable1_itemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_itemsMouseClicked
        try {
            int row = jTable1_items.getSelectedRow();
            ID_field.setText(jTable1_items.getModel().getValueAt(row, 0).toString());
            Name_field.setText(jTable1_items.getModel().getValueAt(row, 1).toString());
            Quantity_field.setText(jTable1_items.getModel().getValueAt(row, 2).toString());
            Warrenty_field.setText(jTable1_items.getModel().getValueAt(row, 3).toString());
            Description_field.setText(jTable1_items.getModel().getValueAt(row, 4).toString());

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_jTable1_itemsMouseClicked

    private void Update_buttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_buttActionPerformed
        String SQLStat = "UPDATE items SET itemName = ? , itemQuantity = ? , itemWarrentyEndDate = ? , "
                + " itemDescription = ? WHERE itemID=?;";

        try {
            PreparedStatement stmt = dataBaseConnection.dataBaseConnectionMethod().prepareStatement(SQLStat);
            stmt.setString(1, Name_field.getText());

            stmt.setInt(2, Integer.parseInt(Quantity_field.getText()));
            if (Warrenty_field.getText().equalsIgnoreCase("")) {
                stmt.setString(3, null);
            } else {
                stmt.setString(3, Warrenty_field.getText());
            }
            if (Description_field.getText().equalsIgnoreCase("")) {
                stmt.setString(4, null);
            } else {
                stmt.setString(4, Description_field.getText());
            }
            stmt.setInt(5, Integer.parseInt(ID_field.getText()));
            stmt.execute();
            stmt.close();
            JOptionPane.showMessageDialog(this, "Done");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            System.out.println(e.getMessage());
        }
        clear_Fields();
    }//GEN-LAST:event_Update_buttActionPerformed

    private void Quantity_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quantity_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Quantity_fieldActionPerformed

    private void Delete_buttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_buttActionPerformed
        String SQLStat = "UPDATE items SET itemStatus=\"DELETED\" WHERE itemID=?;";
        PreparedStatement stmt;
        try {
            stmt = dataBaseConnection.dataBaseConnectionMethod().prepareStatement(SQLStat);
            stmt.setInt(1, Integer.parseInt(ID_field.getText()));
            stmt.execute();
            stmt.close();

        } catch (SQLException ex) {
            Logger.getLogger(Admin_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        clear_Fields();
    }//GEN-LAST:event_Delete_buttActionPerformed

    /**
     * @param args the command line arguments
     */
    void clear_Fields() {
        ID_field.setText(null);
        Name_field.setText(null);
        Quantity_field.setText(null);
        Warrenty_field.setText(null);
        Description_field.setText(null);
        Name_ppl_Field.setText(null);
        NIC_ppl_Field.setText(null);
        Telephne_ppl_Field.setText(null);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD_ppl_butt;
    private javax.swing.JButton Delete_butt;
    private javax.swing.JTextArea Description_field;
    private javax.swing.JTextField ID_field;
    private javax.swing.JButton Insert_butt;
    private javax.swing.JTextField NIC_ppl_Field;
    private javax.swing.JTextField Name_field;
    private javax.swing.JTextField Name_ppl_Field;
    private javax.swing.JTextField Quantity_field;
    private javax.swing.JTextField Telephne_ppl_Field;
    private javax.swing.JButton Update_butt;
    private javax.swing.JTextField Warrenty_field;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.persistence.EntityManager entityManager;
    private java.util.List<javaapplication3.Items> itemsList;
    private javax.persistence.Query itemsQuery;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1_items;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel menu_panel;
    private java.util.List<javaapplication3.People> peopleList;
    private java.util.List<javaapplication3.People> peopleList1;
    private java.util.List<javaapplication3.People> peopleList2;
    private java.util.List<javaapplication3.People> peopleList3;
    private javax.persistence.Query peopleQuery;
    private javax.persistence.Query peopleQuery1;
    private javax.persistence.Query peopleQuery2;
    private javax.persistence.Query peopleQuery3;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
