/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.UnsupportedEncodingException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Induwara Jayalath
 */
public class Login_interface extends javax.swing.JFrame {

    /**
     * Creates new form Login_interface
     */
    public Login_interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Login_button = new javax.swing.JButton();
        Clear_button = new javax.swing.JButton();
        UserName_field = new javax.swing.JTextField();
        Password_field = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("UserName");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 65, -1, -1));

        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 108, -1, -1));

        jLabel3.setText("Master Audio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 20, -1, -1));

        Login_button.setText("Login");
        Login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(Login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 156, -1, -1));

        Clear_button.setText("Clear");
        Clear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(Clear_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 156, -1, -1));

        UserName_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserName_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(UserName_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 62, 122, -1));

        Password_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(Password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 105, 122, -1));

        jLabel4.setText("© IL System Solutions 2017");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 186, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserName_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserName_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserName_fieldActionPerformed

    private void Password_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_fieldActionPerformed
        Login_buttonActionPerformed(evt);

    }//GEN-LAST:event_Password_fieldActionPerformed

    private void Clear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_buttonActionPerformed
        UserName_field.setText(null);
        Password_field.setText(null);
        UserName_field.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_Clear_buttonActionPerformed

    private void Login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_buttonActionPerformed
        try {
            String LoginLogsFilepath = "C:\\Users\\Induwara Jayalath\\Documents\\MevanStock\\LoginLogs.txt";
            Connection conn = dataBaseConnection.dataBaseConnectionMethod();
            Statement stmt = conn.createStatement();
            String query = "select * from usernames";
            ResultSet rs = stmt.executeQuery(query);

            String un = UserName_field.getText();
            String pw = String.valueOf(Password_field.getPassword());
            String msg = "hi";
            Date d = new Date();

            while (rs.next()) {
                String u = rs.getString("userName");
                String p = rs.getString("userPassword");
                int t = rs.getInt("userType");
                int id = rs.getInt("ID");

                if ((un.equalsIgnoreCase(u)) && (pw.equals(p))) {

                    BufferedWriter bw = new BufferedWriter(new FileWriter(LoginLogsFilepath, true));
                    String text = "username :" + un + " logged in time :" + d.toString();
                    bw.write(text);
                    bw.newLine();
                    bw.close();

                    switch (t) {
                        case 1:
                            Admin_panel.current_User_level = 1;
                            MainInterface ms = new MainInterface();
                            ms.setVisible(true);
                            this.dispose();
                            break;

                        default:
                            Admin_panel.current_User_level = 0;
                            MainInterface ms2 = new MainInterface();
                            ms2.setVisible(true);
                            this.dispose();
                            break;

                    }
                    msg = "welcome " + un;
                    Admin_panel.current_User = id;
                    break;
                } else {
                    msg = "Invalid Un or PW";
                }

            }
            JOptionPane.showMessageDialog(this, msg);

        } catch (Exception e) {
            System.out.println(e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Login_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear_button;
    private javax.swing.JButton Login_button;
    private javax.swing.JPasswordField Password_field;
    private javax.swing.JTextField UserName_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
